backend:
  name: test-repository
  branch: main
collections:
    - name: "blog"
      label: "Blog"
      folder: "/content/_posts/blog"
      slug: "{{portfolio}}-{{month}}--{{day}}--{{slug}}"
      fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
media_folder: "/public/images"
public_folder: "/public"


